controller_list:
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
  - name: fake_gripper_controller
    joints:
      - gripper_L_joint
      - gripper_R_joint
      - motor_circle_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: zero_pose
  - group: gripper
    pose: open